<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>InvoiceExportKit.ConsoleSample</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\InvoiceExportKit.Core\InvoiceExportKit.Core.csproj" />
    <ProjectReference Include="..\..\src\InvoiceExportKit.Excel.OpenXml\InvoiceExportKit.Excel.OpenXml.csproj" />
    <ProjectReference Include="..\..\src\InvoiceExportKit.Templates\InvoiceExportKit.Templates.csproj" />
  </ItemGroup>
</Project>
